### ISSUE TITLE
gitlab: Unable to resolve note

### ISSUE THREAD

**Issue by joelsdc** [glensc/slack-unfurl-gitlab#2]
Hi, 

I've setup everything according to your instructions (no problems there).

When I send a link to a channel I receive the event, but I think something is wrong:

```
[2018-08-31 21:35:43] unfurl.INFO: Matched route "{route}". {"route":"POST_slack_unfurl_","route_parameters":{"_controller":"[object] (Closure: {})","_route":"POST_slack_unfurl_"},"request_uri":"http://backends/slack-unfurl/","method":"POST"} []
[2018-08-31 21:35:43] unfurl.DEBUG: > POST /slack-unfurl/ [] []
[2018-08-31 21:35:43] unfurl.DEBUG: link_shared {"event":{"type":"link_shared","user":"XXX","channel":"XXX","message_ts":"1535751342.000100","links":[{"url":"https://some.domain.com/blabla/45","domain":"some.domain.com"}]}} []
[2018-08-31 21:35:43] unfurl.DEBUG: gitlab: Unable to resolve note [] []
[2018-08-31 21:35:43] unfurl.DEBUG: unfurls {"channel":"XXX","ts":"1535751342.000100","unfurls":[]} []
[2018-08-31 21:35:43] unfurl.DEBUG: < 200 [] []
```

Specifically the:
`[2018-08-31 21:35:43] unfurl.DEBUG: gitlab: Unable to resolve note [] []`

Any idea what can be happening?

Thanks!

**Comment by joelsdc** [comment]
EXTRA INFO: I'm using NGINX for SSL offloading in front of `slack-unfurl` so I can use HTTPS.  Just in case it was that, I tried directly with HTTP and Slack accessing port `4390` with same problem.

**Comment by joelsdc** [comment]
So part of the problem seems the parsing of the link...

https://git.domain.com/aa/bb/issues/45#note_3252:

```
...
[2018-08-31 21:35:43] unfurl.DEBUG: gitlab: Unable to resolve note [] []
...
```

https://git.domain.com/aa/bb/issues/45:
```
...
[2018-09-01 00:38:28] unfurl.CRITICAL: InvalidArgumentException: missing_scope (uncaught exception) at /app/src/SlackClient.php line 28 {"exception":"[object] (InvalidArgumentException(code: 0): missing_scope at /app/src/SlackClient.php:28)"} []
[2018-09-01 00:38:28] unfurl.ERROR: missing_scope {"exception":"[object] (InvalidArgumentException(code: 0): missing_scope at /app/src/SlackClient.php:28)","trace":"#0 /app/src/Command/LinkShared.php(48): SlackUnfurl\\SlackClient->unfurl('C47SBUKEU', '1535762305.0002...', Array)\n#1 /app/src/Command/EventCallback.php(34): SlackUnfurl\\Command\\LinkShared->execute(Array)\n#2 /app/src/Controller/UnfurlController.php(44): SlackUnfurl\\Command\\EventCallback->execute(Array)\n#3 /app/src/Application.php(42): SlackUnfurl\\Controller\\UnfurlController->__invoke(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 /app/vendor/symfony/http-kernel/HttpKernel.php(149): SlackUnfurl\\Application->SlackUnfurl\\{closure}(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 /app/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /app/vendor/silex/silex/src/Silex/Application.php(477): Silex\\Application->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#8 /app/web/index.php(4): Silex\\Application->run()\n#9 {main}"} []
...
```

**Comment by joelsdc** [comment]
After adding some debug lines to your code, I found that the problem was because I was missing the `links:write` permission on Slack.

So if I send a link to an issue it's now working, but if I send a link to an issue's note, it still fails with the initial error.

`https://git.domain.com/aa/bb/issues/45` ---> Works!
`https://git.domain.com/aa/bb/issues/45#note_3252` ---> Error!

Suggestions?

Thanks ;)

**Comment by glensc** [comment]
so, the route is matched:
- https://github.com/glensc/slack-unfurl-gitlab/blob/v0.5.1/src/Route/GitLabRoutes.php#L44

but there's no handler written:
- https://github.com/glensc/slack-unfurl-gitlab/blob/v0.5.1/src/Event/Subscriber/GitlabUnfurler.php#L19-L22

**Comment by glensc** [comment]
added in 0.6.0

**Comment by joelsdc** [comment]
Thank you!!
